hw02: array_sort.h File Reference
array_sort.h File Reference
Functions
int int_rand (int max_rand)
void rand_fill (int array[], int max_rand, int num_rands)
void array_sort (double array[], int array_size)
void array_sort_int (int array[], int array_size)
Function Documentation
array_sort()
void array_sort (double array[], int array_size)
Function that sorts the arrays
Parameters
array that is being sorted
array_size size of the array
References print_double_array().
Referenced by main().
array_sort_int()
void array_sort_int (int array[], int array_size)
Function that sorts the arrays
Parameters
array that is being sorted
array_size size of the array
Referenced by main().
int_rand()
int int_rand (int max_rand)
File array_sort.h
Author
Emre Sunar
Header file for functions that sorts arrays.
file array_sort.c
Author
Emre Sunar
Functions for sorting arrays, producing random integers, and randomized arrays Create a random number from 0 to a specified maximum
Parameters
max_rand which is the maximum a random number can be
Returns
x which is a random number from 0 to the max value inclusive
Referenced by rand_fill().
rand_fill()
void rand_fill (int array[], int max_rand, int num_rands)
Fills the array with randomized integers
Parameters
array that is being filled
max_rand max value that the integer can be
num_rands Number of random values
References int_rand().
Referenced by main().