hw02: print_arrays.c File Reference
print_arrays.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include "print_arrays.h"
Functions
void store_floats (double b[], int array_size, int argc, char *argv[])
void print_int_array (int a[], int num_entries)
void print_double_array (double b[], int num_entries)
Function Documentation
print_double_array()
void print_double_array (double b[], int num_entries)
Print an array of doubles, one per line.
Parameters
a Array to print
num_entries Number of entries in the array
Referenced by array_sort(), and main().
print_int_array()
void print_int_array (int a[], int num_entries)
Print an array of ints, one per line.
Parameters
a Array to print
num_entries Number of entries in the array
Referenced by main().
store_floats()
void store_floats (double b[], int array_size, int argc, char * argv[])
file print_arrays.c
Author
Emre Sunar
Functions for printing arrays. Store doubles into an array
Parameters
b[] an array of doubles
array_size the max size of the array
argc number of entries into the array
argv keyboard entries into the array
Referenced by main().